[package]
name = "rmc-core"
version = "0.1.0"
authors = ["Noah Kennedy <noah.kennedy.professional@gmail.com>", "Isaiah Rondeau <isaiahrondeau@gmail.com>", "Wallace Watler <watlerathome@gmail.com>", "Cody Nettesheim <nettesheimcj@msoe.edu>"]
edition = "2018"
build = "build.rs"

[dependencies]
chrono = ""
sysfs-pwm = ""
sysfs_gpio = ""
stderrlog = "0.4"
rocket = ""

[build-dependencies.mml]
version = "0.1"